name: riparian_connect

channels:
  - conda-forge

dependencies:
  - python
  - folium
  - geopandas
  - joblib
  - numpy
  - matplotlib
  - pandas
  - rasterio
  - rioxarray
  - shapely
  - scikit-image
